 name: Update Location Data

on:
  schedule:
    - cron: '0 * * * *' # Runs every hour
  workflow_dispatch: # Allows manual triggering

jobs:
  update-locations:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install axios

      - name: Fetch location data
        run: |
          node -e '
            const axios = require("axios");
            async function update() {
              try {
                const response = await axios.get("https://mypetid-backend.herokuapp.com/api/locations/clyde-nfc-123");
                const locations = response.data;
                const fs = require("fs");
                let html = fs.readFileSync("index.html", "utf8");
                const recentLocations = locations.filter(loc => {
                  const locTime = new Date(loc.timestamp);
                  const now = new Date();
                  const twoHoursAgo = new Date(now.getTime() - 2 * 60 * 60 * 1000);
                  return loc.active && locTime >= twoHoursAgo;
                });
                const mapUrl = recentLocations.length > 0
                  ? `https://www.google.com/maps/embed/v1/place?key=YOUR_API_KEY&q=${recentLocations[0].latitude},${recentLocations[0].longitude}&zoom=12`
                  : "https://www.google.com/maps/embed/v1/place?key=YOUR_API_KEY&q=Toronto,Canada&zoom=12";
                html = html.replace(
                  /<iframe src="https:\/\/www.google.com\/maps\/embed\/v1\/place\?key=YOUR_API_KEY&q=[^"]*"/,
                  `<iframe src="${mapUrl}" allowfullscreen>`
                );
                fs.writeFileSync("index.html", html);
              } catch (error) {
                console.error("Error fetching location data:", error);
              }
            }
            update();
          '

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add index.html
          git commit -m "Update location data [skip ci]" || echo "No changes to commit"
          git push
